/**
 * Copyright (c) 2024 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once
#include <jsi/jsi.h>
#include <unordered_map>

namespace rnoh {
/**
 * @actor RNOH_LIBRARY
 * To understand what this class does, one needs to understand ViewConfig.
 * ViewConfig is an RN concept. It specifies data that can be sent between JS
 * and NATIVE sides. This class actually creates "ViewConfigs" on the JS side.
 * Custom components should extend BaseComponentJSIBinder if they are meant to
 * inherit View component configuration, which is likely the case.
 *
 * ViewConfigs are generated by codegen.
 */
class ComponentJSIBinder {
 public:
  virtual facebook::jsi::Object createBindings(facebook::jsi::Runtime&) = 0;
};

/**
 * @actor RNOH_LIBRARY, CODEGEN
 * Type used by Package.h.
 */
using ComponentJSIBinderByString =
    std::unordered_map<std::string, std::shared_ptr<ComponentJSIBinder>>;

} // namespace rnoh
