#include "RNOH/PackageProvider.h"
#include "CodegenLibSamplePackage.h"
#include "RNOHPackagesFactory.h"
#include "ReactNativeHarmonySamplePackagePackage.h"
#include "generated/RNOHGeneratedPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(
      ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  packages.push_back(
      std::make_shared<CodegenLibSamplePackage>(ctx)); // manual linking
  packages.push_back(std::make_shared<ReactNativeHarmonySamplePackagePackage>(
      ctx)); // comment this line out when testing autolinking
  return packages;
}