// clang-format off
#include "RNOH/PackageProvider.h"
#include "RNOHPackagesFactory.h"
#include "generated/RNOHGeneratedPackage.h"
#include "AsyncStoragePackage.h"
#include "BlurPackage.h"
#include "ClipboardPackage.h"
#include "CookiesPackage.h"
#include "CheckboxPackage.h"
#include "DateTimePickerPackage.h"
#include "ExceptionHandlerPackage.h"
#include "FlashListPackage.h"
#include "GeoLocationPackage.h"
#include "LinearGradientPackage.h"
#include "LottieAnimationViewPackage.h"
#include "MaskedPackage.h"
#include "RNImagePickerPackage.h"
#include "RNCNetInfoPackage.h"
#include "ToolbarAndroidPackage.h"
#include "RNMlkitOcrPackage.h"
#include "AutoFillPackage.h" 
#include "RNInCallManagerPackage.h"
#include "BlurhashPackage.h"
#include "UiLibPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  // manual linking: BEGIN
  packages.push_back(std::make_shared<AsyncStoragePackage>(ctx));
  packages.push_back(std::make_shared<BlurPackage>(ctx));
  packages.push_back(std::make_shared<ClipboardPackage>(ctx));
  packages.push_back(std::make_shared<CookiesPackage>(ctx));
  packages.push_back(std::make_shared<CheckboxPackage>(ctx));
  packages.push_back(std::make_shared<DateTimePickerPackage>(ctx));
  packages.push_back(std::make_shared<ExceptionHandlerPackage>(ctx));
  packages.push_back(std::make_shared<FlashListPackage>(ctx));
  packages.push_back(std::make_shared<GeoLocationPackage>(ctx));
  packages.push_back(std::make_shared<LinearGradientPackage>(ctx));
  packages.push_back(std::make_shared<LottieAnimationViewPackage>(ctx));
  packages.push_back(std::make_shared<MaskedPackage>(ctx));
  packages.push_back(std::make_shared<RNImagePickerPackage>(ctx));
  packages.push_back(std::make_shared<RNCNetInfoPackage>(ctx));
  packages.push_back(std::make_shared<ToolbarAndroidPackage>(ctx));
  packages.push_back(std::make_shared<RNMlkitOcrPackage>(ctx));
  packages.push_back(std::make_shared<AutoFillPackage>(ctx));
  packages.push_back(std::make_shared<RNInCallManagerPackage>(ctx));
  packages.push_back(std::make_shared<BlurhashPackage>(ctx));
  packages.push_back(std::make_shared<UiLibPackage>(ctx));
  // manual linking: END
  return packages;
}